### PR TITLE
Fixed PAW calculation

### LINKED ISSUE #31: The PAW calculation when gravs are specified is incorrect
The conversion to volumetric needs to happen before the layer mapping, not after.

### PR DESCRIPTION
**Pull request by hol353**
Resolves #31

### CODE REVIEW

File: API/Services/SoilServices.cs [hunk 1]
```diff
@@ -202,7 +206,7 @@ private static double[] SWMappedTo(this IReadOnlyList<double> values, IReadOnlyL
         sw.Add(0.0);                     // 3rd pseudo layer below profile.
         thickness.Add(thickness.Last()); // 1st pseudo layer below profile.
         thickness.Add(thickness.Last()); // 2nd pseudo layer below profile.
-        thickness.Add(3000);             // 3rd pseudo layer below profile.
+        thickness.Add(300);             // 3rd pseudo layer below profile.
```
Comment (par456) [inline API/Services/SoilServices.cs:209]: What was the reasoning for changing this from 3000 to 300?

Comment (hol353) [reply API/Services/SoilServices.cs]: Good catch. That change was me doing some debugging. Fixed now.

**Comment by hol353** [comment]
@par456 Can you look at this one again?
